options:
  token: "YOUR_TOKEN"
  channel_send: "YOUR_CHANNEL"
  join: true
  quit: true
  chat: true
  message_join: "%user% join server"
  message_quit: "%user% leave server"
  message_chat: "%user% >> %message%"